name: tinkoff_id_web
description: Tinkoff Id WebToApp Flutter Realization
version: 1.0.1
homepage: https://kodefabrique.com

environment:
  sdk: ^3.0.0
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  pkce: ^1.1.0+1
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:


